avance2/controlmedico/controlmedico/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include('core.urls')),
]

avance2/controlmedico/core/urls.py
from django.urls import path
from . import views

app_name = 'core' 

urlpatterns = [
    # URLs para Puesto
    path('puesto/create/', views.CreatePuesto.as_view(), name='create_puesto'),
    path('puesto/list/', views.ListPuesto.as_view(), name='list_puesto'),
    path('puesto/<int:pk>/', views.DetailPuesto.as_view(), name='detail_puesto'),
    path('puesto/update/<int:pk>/', views.UpdatePuesto.as_view(), name='update_puesto'),
    path('puesto/<int:pk>/delete/', views.DeletePuesto.as_view(), name='delete_puesto'),

    # URLs para Empleado
    path('empleado/create/', views.CreateEmpleado.as_view(), name='create_empleado'),
    path('empleado/list/', views.ListEmpleado.as_view(), name='list_empleado'),
    path('empleado/<int:pk>/', views.DetailEmpleado.as_view(), name='detail_empleado'),
    path('empleado/<int:pk>/update/', views.UpdateEmpleado.as_view(), name='update_empleado'),
    path('empleado/<int:pk>/delete/', views.DeleteEmpleado.as_view(), name='delete_empleado'),

    # URLs para Alergia
    path('alergia/create/', views.CreateAlergia.as_view(), name='create_alergia'),
    path('alergia/list/', views.ListAlergia.as_view(), name='list_alergia'),
    path('alergia/<int:pk>/', views.DetailAlergia.as_view(), name='detail_alergia'),
    path('alergia/<int:pk>/update/', views.UpdateAlergia.as_view(), name='update_alergia'),
    path('alergia/<int:pk>/delete/', views.DeleteAlergia.as_view(), name='delete_alergia'),
]

avance2/controlmedico/home/urls.py
from django.urls import path


from home import views


app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
]

avance2/controlmedico/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import timedelta
# Create your models here.

class Puesto(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(max_length=100)
    
    def __str__(self):
        return self.nombre

class Empleado(models.Model):
    nombrePila = models.CharField(max_length=20,null=True)  
    apPat = models.CharField(max_length=20,null=True)  
    apMat = models.CharField(max_length=20,null=True)  
    fnacimiento = models.DateField()
    puesto = models.ForeignKey(Puesto, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombrePila

class Alergia(models.Model):
    nombre = models.CharField(max_length=100)
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre

avance2/controlmedico/home/models.py
from django.db import models

# Create your models here.

avance2/controlmedico/core/forms.py
from django import forms
from .models import Puesto, Empleado, Alergia

class PuestoForm(forms.ModelForm):
    class Meta:
        model = Puesto
        fields = ['nombre', 'descripcion']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre del puesto'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Descripción del puesto'}),
        }

class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = ['nombrePila', 'apPat', 'apMat', 'fnacimiento', 'puesto']
        widgets = {
            'nombrePila': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre del empleado'}),
            'apPat': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido paterno'}),
            'apMat': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido materno'}),
            'fnacimiento': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'puesto': forms.Select(attrs={'class': 'form-control'}),
        }

class AlergiaForm(forms.ModelForm):
    class Meta:
        model = Alergia
        fields = ['nombre', 'empleado']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de la alergia'}),
            'empleado': forms.Select(attrs={'class': 'form-control'}),
        }

avance2/controlmedico/core/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from .forms import PuestoForm, EmpleadoForm, AlergiaForm
from .models import Puesto, Empleado, Alergia


#Puesto
class CreatePuesto(CreateView):
    template_name = "core/create_puesto.html"
    model = Puesto
    form_class = PuestoForm
    success_url = reverse_lazy('core:list_puesto')

class ListPuesto(ListView):
    template_name = "core/list_puesto.html"  
    model = Puesto
    context_object_name = 'Puestos'

class DetailPuesto(DetailView):
    template_name = "core/detail_puesto.html"
    model = Puesto
    context_object_name = 'Puesto'

class UpdatePuesto(UpdateView):
    template_name = "core/update_puesto.html"
    model = Puesto
    form_class = PuestoForm
    success_url = reverse_lazy('core:list_puesto')

class DeletePuesto(DeleteView):
    template_name = "core/delete_puesto.html"
    model = Puesto
    success_url = reverse_lazy('core:list_puesto')
    
    #Empleado
class CreateEmpleado(CreateView):
    template_name = "core/create_empleado.html"
    model = Empleado
    form_class = EmpleadoForm
    success_url = reverse_lazy('core:list_empleado')

class ListEmpleado(ListView):
    template_name = "core/list_empleado.html"  
    model = Empleado
    context_object_name = 'Empleados'

class DetailEmpleado(DetailView):
    template_name = "core/detail_empleado.html"
    model = Empleado
    context_object_name = 'Empleado'

class UpdateEmpleado(UpdateView):
    template_name = "core/update_empleado.html"
    model = Empleado
    form_class = EmpleadoForm
    success_url = reverse_lazy('core:list_empleado')

class DeleteEmpleado(DeleteView):
    template_name = "core/delete_empleado.html"
    model = Empleado
    success_url = reverse_lazy('core:list_empleado')
    
    #Alergia
class CreateAlergia(CreateView):
    template_name = "core/create_alergia.html"
    model = Alergia
    form_class = AlergiaForm
    success_url = reverse_lazy('core:list_alergia')

class ListAlergia(ListView):
    template_name = "core/list_alergia.html"  
    model = Alergia
    context_object_name = 'Alergias'

class DetailAlergia(DetailView):
    template_name = "core/detail_alergia.html"
    model = Alergia
    context_object_name = 'Alergia'

class UpdateAlergia(UpdateView):
    template_name = "core/update_alergia.html"
    model = Alergia
    form_class = AlergiaForm
    success_url = reverse_lazy('core:list_alergia')

class DeleteAlergia(DeleteView):
    template_name = "core/delete_alergia.html"
    model = Alergia
    success_url = reverse_lazy('core:list_alergia')

avance2/controlmedico/home/views.py
from django.shortcuts import render
from django.views import generic
# Create your views here.


class Index(generic.View):
    template_name = "home/index.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Ray Parra"
        }
        return render(request, self.template_name, self.context)

avance2/controlmedico/core/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <!-- NAV BAR -->
                <nav class="navbar navbar-expand-lg bg-body-tertiary">
                    <div class="container-fluid">
                      <a class="navbar-brand" href="#">CONTROL MEDICO</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item"> 
                            <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Home</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:list_puesto' %}">Puestos</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:list_empleado' %}">Empleados</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:list_alergia' %}">Alergias</a>
                          </li>
                        </ul>
                        <form class="d-flex" role="search">
                          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                          <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                      </div>
                    </div>
                  </nav>
            </div>
        </div>
        <div class="row">
            <div class="col-2"></div>
            <div class "col-8">
                {% block content %}
                {% endblock content %}
            </div>
            <div class="col-2"></div>
        </div>
        <div class="row">
            <div class="col">
                <footer class="text-center text-white" style="background-color: #f1f1f1;">
                    <!-- Grid container -->
                    <div class="container pt-4">
                      <!-- Section: Social media -->
                      <section class="mb-4">
                        <!-- Facebook -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-facebook-f"></i
                        ></a>
                  
                        <!-- Twitter -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-twitter"></i
                        ></a>

                        <i class="glyphicon glyphicon-cloud"></i>

                  
                        <!-- Google -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-google"></i
                        ></a>
                  
                        <!-- Instagram -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-instagram"></i
                        ></a>
                  
                        <!-- Linkedin -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-linkedin"></i
                        ></a>
                        <!-- Github -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-github"></i
                        ></a>
                      </section>
                      <!-- Section: Social media -->
                    </div>
                    <!-- Grid container -->
                  
                    <!-- Copyright -->
                    <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                      © 2023 Copyright:
                      <a class="text-dark" href="Rodriguez Altamirano Christian Rodolfo">Rodriguez Altamirano Christian Rodolfo</a>
                    </div>
                    <!-- Copyright -->
                  </footer>
            </div>
        </div>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

avance2/controlmedico/core/templates/core/create_alergia.html
{% extends "base/base.html" %}

{% block title %}
  Crear Alergia
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Crear</button>
    <a href="{% url 'core:list_alergia' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

avance2/controlmedico/core/templates/core/create_empleado.html
{% extends "base/base.html" %}

{% block title %}
  Crear Empleado
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Crear</button>
    <a href="{% url 'core:list_empleado' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

avance2/controlmedico/core/templates/core/create_puesto.html
{% extends "base/base.html" %}

{% block title %}
  Crear Puesto
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
           {% csrf_token %}
           {{ form.as_p }}
             <button type="submit" class="btn btn-primary">Crear</button>
            <a href="{% url 'core:list_puesto' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

avance2/controlmedico/core/templates/core/delete_alergia.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar Alergia
{% endblock title %}

{% block content %}
  <p>¿Estás seguro de que deseas eliminar la Alergia '{{ alergia.nombre }}'?</p>
  <form action="" method="post" class="form">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'core:list_alergia' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

avance2/controlmedico/core/templates/core/delete_empleado.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar Empleado
{% endblock title %}

{% block content %}
  <p>¿Estás seguro de que deseas eliminar al Empleado '{{ empleado.id }}'?</p>
  <form action="" method="post" class="form">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'core:list_empleado' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

avance2/controlmedico/core/templates/core/delete_puesto.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar Puesto
{% endblock title %}

{% block content %}
  <p>¿Estás seguro de que deseas eliminar el Puesto'{{ puesto.nombre }}'?</p>
  <form action="" method="post" class="form">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'core:list_puesto' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

avance2/controlmedico/core/templates/core/detail_alergia.html
{% extends "base/base.html" %}

{% block title %}
  Detalles del Alergia
{% endblock title %}

{% block content %}
  <h2>{{ estadio.nombre }}</h2>
  <p>Esta es la alergia '{{ alergia.nombre }}' que pertenece al Empleado '{{ alergia.empleado.id }}'.</p>
  <a href="{% url 'core:list_alergia' %}" class="btn btn-secondary">Volver a la lista de Alergia</a>
{% endblock content %}

avance2/controlmedico/core/templates/core/detail_empleado.html
{% extends "base/base.html" %}

{% block title %}
  Detalles del Empleado
{% endblock title %}

{% block content %}
  <h2>{{ empleado.nombrePila }}</h2>
  <p>Este es el Empleado '{{ empleado.nombrePila }}' que pertenece al Puesto '{{ empleado.puesto.nombre }}'.</p>
  <a href="{% url 'core:list_empleado' %}" class="btn btn-secondary">Volver a la lista de Empleados</a>
{% endblock content %}

avance2/controlmedico/core/templates/core/list_alergia.html
{% extends "base/base.html" %}

{% block title %}
  Lista de Alergias
{% endblock title %}

{% block content %}
  <table class="table table-hover">
    <thead>
      <th>ID</th>
      <th>Nombre</th>
      <th>Empleado</th>
      <th>Acciones</th>
    </thead>
    <tbody>
      <a href="{% url 'core:create_alergia' %}" class="btn btn-success">Crear alergia</a>
      {% for alergia in Alergias %}
        <tr>
          <td>{{ alergia.id }}</td>
          <td>{{ alergia.nombre }}</td>
          <td>{{ alergia.empleado.id }}</td>
          <td>
            <a href="{% url 'core:detail_alergia' alergia.id %}" class="btn btn-info">Detalles</a>
            <a href="{% url 'core:update_alergia' alergia.id %}" class="btn btn-warning">Editar</a>
            <a href="{% url 'core:delete_alergia' alergia.id %}" class="btn btn-danger">Eliminar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

avance2/controlmedico/core/templates/core/list_empleado.html
{% extends "base/base.html" %}

{% block title %}
  Lista de Empleados
{% endblock title %}

{% block content %}
  <table class="table table-hover">
    <thead>
      <th>ID</th>
      <th>Nombre</th>
      <th>Apellido Paterno</th>
      <th>Apellido Materno</th>
      <th>Fecha de nacimiento</th>
      <th>Puesto</th>
    </thead>
    <tbody>
      <a href="{% url 'core:create_empleado' %}" class="btn btn-success">Crear Empleado</a>
      {% for empleado in Empleados %}
        <tr>
          <td>{{ empleado.id }}</td>
          <td>{{ empleado.nombrePila }}</td>
          <td>{{ empleado.apPat }}</td>
          <td>{{ empleado.apMat }}</td>
          <td>{{ empleado.fnacimiento }}</td>
          <td>{{ empleado.puesto.nombre }}</td>
          <td>
            <a href="{% url 'core:detail_empleado' empleado.id %}" class="btn btn-info">Detalles</a>
            <a href="{% url 'core:update_empleado' empleado.id %}" class="btn btn-warning">Editar</a>
            <a href="{% url 'core:delete_empleado' empleado.id %}" class="btn btn-danger">Eliminar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

avance2/controlmedico/core/templates/core/list_puesto.html
{% extends "base/base.html" %}

{% block title %}
  Lista de Puestos
{% endblock title %}

{% block content %}
  <table class="table table-hover">
    <thead>
      <th>ID</th>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Acciones</th>
    </thead>
    <tbody>
      <a href="{% url 'core:create_puesto' %}" class="btn btn-success">Crear Puesto</a>
      {% for puesto in Puestos %}
        <tr>
          <td>{{ puesto.id }}</td>
          <td>{{ puesto.nombre }}</td>
          <td>{{ puesto.descripcion }}</td>
          <td>
            <a href="{% url 'core:detail_puesto' puesto.id %}" class="btn btn-info">Detalles</a>
            <a href="{% url 'core:update_puesto' puesto.id %}" class="btn btn-warning">Editar</a>
            <a href="{% url 'core:delete_puesto' puesto.id %}" class="btn btn-danger">Eliminar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

avance2/controlmedico/core/templates/core/update_alergia.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar Alergia
{% endblock title %}

{% block content %}
  <form action="" method="post" class "form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Actualizar</button>
    <a href="{% url 'core:list_alergia' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

avance2/controlmedico/core/templates/core/update_empleado.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar Empleado
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Actualizar</button>
    <a href="{% url 'core:list_empleado' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

avance2/controlmedico/core/templates/core/update_puesto.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar Puesto
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Actualizar</button>
    <a href="{% url 'core:list_puesto' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

avance2/controlmedico/core/templates/home/index.html
{% extends 'base/base.html' %}

{% block title %}Bienvenido a la Aplicación de Control Médico{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-12 text-center">
            <h1 class="display-4">¡Bienvenido a la Aplicación de Control Médico!</h1>
            <p class="lead">Tu solución confiable para gestionar registros médicos y de pacientes.</p>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-12 text-center">
            <p>¿Listo para acceder a tu cuenta?</p>
        </div>
    </div>
</div>
{% endblock content %}