examParc2/nfl_app/home/urls.py
from django.urls import path




from home import views


app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
]

examParc2/nfl_app/nfl/urls.py
from django.urls import path
from . import views

app_name = 'nfl' 

urlpatterns = [
    # URLs para Ciudad
    path('ciudad/create/', views.CreateCiudad.as_view(), name='create_ciudad'),
    path('ciudad/list/', views.ListCiudades.as_view(), name='list_ciudades'),
    path('ciudad/<int:pk>/', views.DetailCiudad.as_view(), name='detail_ciudad'),
    path('ciudad/update/<int:pk>/', views.UpdateCiudad.as_view(), name='update_ciudad'),
    path('ciudad/<int:pk>/delete/', views.DeleteCiudad.as_view(), name='delete_ciudad'),

    # URLs para Equipo
    path('equipo/create/', views.CreateEquipo.as_view(), name='create_equipo'),
    path('equipo/list/', views.ListEquipos.as_view(), name='list_equipo'),
    path('equipo/<int:pk>/', views.DetailEquipo.as_view(), name='detail_equipo'),
    path('equipo/<int:pk>/update/', views.UpdateEquipo.as_view(), name='update_equipo'),
    path('equipo/<int:pk>/delete/', views.DeleteEquipo.as_view(), name='delete_equipo'),

    # URLs para Estadio
    path('estadio/create/', views.CreateEstadio.as_view(), name='create_estadio'),
    path('estadio/list/', views.ListEstadios.as_view(), name='list_estadio'),
    path('estadio/<int:pk>/', views.DetailEstadio.as_view(), name='detail_estadio'),
    path('estadio/<int:pk>/update/', views.UpdateEstadio.as_view(), name='update_estadio'),
    path('estadio/<int:pk>/delete/', views.DeleteEstadio.as_view(), name='delete_estadio'),
]

examParc2/nfl_app/nfl_pr/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('nfl/', include('nfl.urls')),
]

examParc2/nfl_app/home/models.py
from django.db import models

# Create your models here.

examParc2/nfl_app/nfl/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import timedelta

# Create your models here.

class Ciudad(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class Equipo(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre

class Estadio(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre
    
    
 
 
 

examParc2/nfl_app/nfl/forms.py
from django import forms
from .models import Ciudad, Equipo, Estadio

class CiudadForm(forms.ModelForm):
    class Meta:
        model = Ciudad
        fields = ["nombre"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre de la ciudad"}),
        }

class EquipoForm(forms.ModelForm):
    class Meta:
        model = Equipo
        fields = ["nombre", "ciudad"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del equipo"}),
            "ciudad": forms.Select(attrs={"class": "form-control"}),
        }

class EstadioForm(forms.ModelForm):
    class Meta:
        model = Estadio
        fields = ["nombre", "equipo"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del estadio"}),
            "equipo": forms.Select(attrs={"class": "form-control"}),
        }

examParc2/nfl_app/home/views.py
from django.shortcuts import render
from django.views import generic
# Create your views here.


class Index(generic.View):
    template_name = "home/index.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Ray Parra"
        }
        return render(request, self.template_name, self.context)

examParc2/nfl_app/nfl/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from .forms import CiudadForm, EquipoForm, EstadioForm
from .models import Ciudad, Equipo, Estadio

# Vistas para Ciudad
class CreateCiudad(CreateView):
    template_name = "nfl/create_ciudad.html"
    model = Ciudad
    form_class = CiudadForm
    success_url = reverse_lazy('nfl:list_ciudades')

class ListCiudades(ListView):
    template_name = "nfl/list_ciudades.html"  
    model = Ciudad
    context_object_name = 'ciudades'

class DetailCiudad(DetailView):
    template_name = "nfl/detail_ciudad.html"
    model = Ciudad
    context_object_name = 'ciudad'

class UpdateCiudad(UpdateView):
    template_name = "nfl/update_ciudad.html"
    model = Ciudad
    form_class = CiudadForm
    success_url = reverse_lazy('nfl:list_ciudades')

class DeleteCiudad(DeleteView):
    template_name = "nfl/delete_ciudad.html"
    model = Ciudad
    success_url = reverse_lazy('nfl:list_ciudades')

# Vistas para Equipo
class CreateEquipo(CreateView):
    template_name = "nfl/create_equipo.html"
    model = Equipo
    form_class = EquipoForm
    success_url = reverse_lazy('nfl:list_equipo')

class ListEquipos(ListView):
    template_name = "nfl/list_equipo.html"
    model = Equipo
    context_object_name = 'equipos'

class DetailEquipo(DetailView):
    template_name = "nfl/detail_equipo.html"
    model = Equipo
    context_object_name = 'equipo'

class UpdateEquipo(UpdateView):
    template_name = "nfl/update_equipo.html"
    model = Equipo
    form_class = EquipoForm
    success_url = reverse_lazy('nfl:list_equipo')

class DeleteEquipo(DeleteView):
    template_name = "nfl/delete_equipo.html"
    model = Equipo
    success_url = reverse_lazy('nfl:list_equipo')


# Vistas para Estadio
class CreateEstadio(CreateView):
    template_name = "nfl/create_estadio.html"
    model = Estadio
    form_class = EstadioForm
    success_url = reverse_lazy('nfl:list_estadio')

class ListEstadios(ListView):
    template_name = "nfl/list_estadio.html"  
    model = Estadio
    context_object_name = 'estadios'

class DetailEstadio(DetailView):
    template_name = "nfl/detail_estadio.html"
    model = Estadio
    context_object_name = 'estadio'

class UpdateEstadio(UpdateView):
    template_name = "nfl/update_estadio.html"
    model = Estadio
    form_class = EstadioForm
    success_url = reverse_lazy('nfl:list_estadio')

class DeleteEstadio(DeleteView):
    template_name = "nfl/delete_estadio.html"
    model = Estadio
    success_url = reverse_lazy('nfl:list_estadio')

examParc2/nfl_app/nfl/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <!-- NAV BAR -->
                <nav class="navbar navbar-expand-lg bg-body-tertiary">
                    <div class="container-fluid">
                      <a class="navbar-brand" href="#">PRO NFL</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item"> 
                            <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Home</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'nfl:list_ciudades' %}">Ciudad</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'nfl:list_equipo' %}">Equipos</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'nfl:list_estadio' %}">Estadios</a>
                          </li>
                        </ul>
                        <form class="d-flex" role="search">
                          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                          <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                      </div>
                    </div>
                  </nav>
            </div>
        </div>
        <div class="row">
            <div class="col-2"></div>
            <div class "col-8">
                {% block content %}
                {% endblock content %}
            </div>
            <div class="col-2"></div>
        </div>
        <div class="row">
            <div class="col">
                <footer class="text-center text-white" style="background-color: #f1f1f1;">
                    <!-- Grid container -->
                    <div class="container pt-4">
                      <!-- Section: Social media -->
                      <section class="mb-4">
                        <!-- Facebook -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-facebook-f"></i
                        ></a>
                  
                        <!-- Twitter -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-twitter"></i
                        ></a>

                        <i class="glyphicon glyphicon-cloud"></i>

                  
                        <!-- Google -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-google"></i
                        ></a>
                  
                        <!-- Instagram -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-instagram"></i
                        ></a>
                  
                        <!-- Linkedin -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-linkedin"></i
                        ></a>
                        <!-- Github -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-github"></i
                        ></a>
                      </section>
                      <!-- Section: Social media -->
                    </div>
                    <!-- Grid container -->
                  
                    <!-- Copyright -->
                    <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                      © 2023 Copyright:
                      <a class="text-dark" href="Rodriguez Altamirano Christian Rodolfo">Rodriguez Altamirano Christian Rodolfo</a>
                    </div>
                    <!-- Copyright -->
                  </footer>
            </div>
        </div>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

examParc2/nfl_app/nfl/templates/home/index.html
{% extends 'base/base.html' %}

{% block title %}Bienvenido a la Aplicación de la NFL{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-12 text-center">
            <h1 class="display-4">¡Bienvenido a la Aplicación de la NFL!</h1>
            <p class="lead">Tu fuente confiable para gestionar registros de estadios, equipos y ciudades de la NFL.</p>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-12 text-center">
            <p>¿Listo para administrar la información de la NFL?</p>
            <a href="{% url 'nfl:list_ciudades' %}" class="btn btn-primary btn-lg">Explora las Ciudades</a>
        </div>
    </div>
</div>
{% endblock content %}

examParc2/nfl_app/nfl/templates/nfl/create_ciudad.html
{% extends "base/base.html" %}

{% block title %}
  Crear Ciudad
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
           {% csrf_token %}
           {{ form.as_p }}
             <button type="submit" class="btn btn-primary">Crear</button>
            <a href="{% url 'nfl:list_ciudades' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

examParc2/nfl_app/nfl/templates/nfl/create_equipo.html
{% extends "base/base.html" %}

{% block title %}
  Crear Equipo
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Crear</button>
    <a href="{% url 'nfl:list_equipo' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

examParc2/nfl_app/nfl/templates/nfl/create_estadio.html
{% extends "base/base.html" %}

{% block title %}
  Crear Estadio
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Crear</button>
    <a href="{% url 'nfl:list_estadio' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

examParc2/nfl_app/nfl/templates/nfl/delete_equipo.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar Equipo
{% endblock title %}

{% block content %}
  <p>¿Estás seguro de que deseas eliminar el Equipo '{{ equipo.nombre }}'?</p>
  <form action="" method="post" class="form">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'nfl:list_equipo' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

examParc2/nfl_app/nfl/templates/nfl/delete_estadio.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar Estadio
{% endblock title %}

{% block content %}
  <p>¿Estás seguro de que deseas eliminar el Estadio '{{ estadio.nombre }}'?</p>
  <form action="" method="post" class="form">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'nfl:list_estadio' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

examParc2/nfl_app/nfl/templates/nfl/detail_ciudad.html
{% extends "base/base.html" %}

{% block title %}
  Detalles de la Ciudad
{% endblock title %}

{% block content %}
  <h2>{{ ciudad.nombre }}</h2>
  <p>Esta es la Ciudad {{ ciudad.nombre }}.</p>
  <a href="{% url 'nfl:list_ciudades' %}" class="btn btn-secondary">Volver a la lista de Ciudades</a>
{% endblock content %}

examParc2/nfl_app/nfl/templates/nfl/detail_equipo.html
{% extends "base/base.html" %}

{% block title %}
  Detalles del Equipo
{% endblock title %}

{% block content %}
  <h2>{{ equipo.nombre }}</h2>
  <p>Este es el Equipo '{{ equipo.nombre }}' que pertenece a la Ciudad '{{ equipo.ciudad.nombre }}'.</p>
  <a href="{% url 'nfl:list_equipo' %}" class="btn btn-secondary">Volver a la lista de Equipos</a>
{% endblock content %}

examParc2/nfl_app/nfl/templates/nfl/detail_estadio.html
{% extends "base/base.html" %}

{% block title %}
  Detalles del Estadio
{% endblock title %}

{% block content %}
  <h2>{{ estadio.nombre }}</h2>
  <p>Este es el Estadio '{{ estadio.nombre }}' que pertenece al Equipo '{{ estadio.equipo.nombre }}'.</p>
  <a href="{% url 'nfl:list_estadio' %}" class="btn btn-secondary">Volver a la lista de Estadios</a>
{% endblock content %}

examParc2/nfl_app/nfl/templates/nfl/list_ciudades.html
{% extends "base/base.html" %}

{% block title %}
  Lista de Ciudades
{% endblock title %}

{% block content %}
  <table class="table table-hover">
    <thead>
      <th>ID</th>
      <th>Nombre</th>
      <th>Acciones</th>
    </thead>
    <tbody>
      <a href="{% url 'nfl:create_ciudad' %}" class="btn btn-success">Crear Ciudad</a>
      {% for ciudad in ciudades %}
        <tr>
          <td>{{ ciudad.id }}</td>
          <td>{{ ciudad.nombre }}</td>
          <td>
            <a href="{% url 'nfl:detail_ciudad' ciudad.id %}" class="btn btn-info">Detalles</a>
            <a href="{% url 'nfl:update_ciudad' ciudad.id %}" class="btn btn-warning">Editar</a>
            <a href="{% url 'nfl:delete_ciudad' ciudad.id %}" class="btn btn-danger">Eliminar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

examParc2/nfl_app/nfl/templates/nfl/list_equipo.html
{% extends "base/base.html" %}

{% block title %}
  Lista de Equipos
{% endblock title %}

{% block content %}
  <table class="table table-hover">
    <thead>
      <th>ID</th>
      <th>Nombre</th>
      <th>Ciudad</th>
      <th>Acciones</th>
    </thead>
    <tbody>
      <a href="{% url 'nfl:create_equipo' %}" class="btn btn-success">Crear Equipo</a>
      {% for equipo in equipos %}
        <tr>
          <td>{{ equipo.id }}</td>
          <td>{{ equipo.nombre }}</td>
          <td>{{ equipo.ciudad.nombre }}</td>
          <td>
            <a href="{% url 'nfl:detail_equipo' equipo.id %}" class="btn btn-info">Detalles</a>
            <a href="{% url 'nfl:update_equipo' equipo.id %}" class="btn btn-warning">Editar</a>
            <a href="{% url 'nfl:delete_equipo' equipo.id %}" class="btn btn-danger">Eliminar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

examParc2/nfl_app/nfl/templates/nfl/list_estadio.html
{% extends "base/base.html" %}

{% block title %}
  Lista de Estadios
{% endblock title %}

{% block content %}
  <table class="table table-hover">
    <thead>
      <th>ID</th>
      <th>Nombre</th>
      <th>Equipo</th>
      <th>Acciones</th>
    </thead>
    <tbody>
      <a href="{% url 'nfl:create_estadio' %}" class="btn btn-success">Crear Estadio</a>
      {% for estadio in estadios %}
        <tr>
          <td>{{ estadio.id }}</td>
          <td>{{ estadio.nombre }}</td>
          <td>{{ estadio.equipo.nombre }}</td>
          <td>
            <a href="{% url 'nfl:detail_estadio' estadio.id %}" class="btn btn-info">Detalles</a>
            <a href="{% url 'nfl:update_estadio' estadio.id %}" class="btn btn-warning">Editar</a>
            <a href="{% url 'nfl:delete_estadio' estadio.id %}" class="btn btn-danger">Eliminar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

examParc2/nfl_app/nfl/templates/nfl/update_ciudad.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar Ciudad
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Actualizar</button>
    <a href="{% url 'nfl:list_ciudades' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

examParc2/nfl_app/nfl/templates/nfl/update_equipo.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar Equipo
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Actualizar</button>
    <a href="{% url 'nfl:list_equipo' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

examParc2/nfl_app/nfl/templates/nfl/update_estadio.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar Estadio
{% endblock title %}

{% block content %}
  <form action="" method="post" class "form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Actualizar</button>
    <a href="{% url 'nfl:list_estadio' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}